# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_first_name', models.CharField(help_text='Applicant Given Name', max_length=35)),
                ('applicant_last_name', models.CharField(help_text='Applicant Family Name', max_length=35)),
                ('applicant_business_name', models.CharField(blank=True, help_text='Applicant Business Name', max_length=50)),
                ('applicant_acn_abn', models.CharField(blank=True, help_text='Applicant ACN/ABN', max_length=15)),
                ('applicant_address', models.CharField(help_text='Applicant Address', max_length=95)),
                ('applicant_postcode', models.CharField(help_text='Applicant Postcode', max_length=9)),
                ('applicant_fax', models.CharField(help_text='Applicant Fax', max_length=26)),
                ('applicant_phone', models.CharField(blank=True, help_text='Applicant Phone', max_length=26)),
                ('applicant_email', models.EmailField(blank=True, help_text='Applicant Email', max_length=254)),
                ('applicant_phone_verified', models.BooleanField(default=False, help_text='Applicant Phone Verified?')),
                ('applicant_email_verified', models.BooleanField(default=False, help_text='Applicant Email Verified?')),
                ('agent_first_name', models.CharField(help_text='Agent Given Name', max_length=35)),
                ('agent_last_name', models.CharField(help_text='Agent Family Name', max_length=35)),
                ('agent_business_name', models.CharField(blank=True, help_text='Agent Business Name', max_length=50)),
                ('agent_acn_abn', models.CharField(blank=True, help_text='Agent ACN/ABN', max_length=15)),
                ('agent_address', models.CharField(help_text='Agent Address', max_length=95)),
                ('agent_postcode', models.CharField(help_text='Agent Postcode', max_length=9)),
                ('agent_fax', models.CharField(help_text='Agent Fax', max_length=26)),
                ('agent_phone', models.CharField(blank=True, help_text='Agent Phone', max_length=26)),
                ('agent_email', models.EmailField(blank=True, help_text='Agent Email', max_length=254)),
                ('agent_phone_verified', models.BooleanField(default=False, help_text='Agent Phone Verified?')),
                ('agent_email_verified', models.BooleanField(default=False, help_text='Agent Email Verified?')),
                ('recipient_first_name', models.CharField(help_text='Recipient Given Name', max_length=35)),
                ('recipient_last_name', models.CharField(help_text='Recipient Family Name', max_length=35)),
                ('recipient_business_name', models.CharField(blank=True, help_text='Recipient Business Name', max_length=50)),
                ('recipient_acn_abn', models.CharField(blank=True, help_text='Recipient ACN/ABN', max_length=15)),
                ('recipient_address', models.CharField(help_text='Recipient Address', max_length=95)),
                ('recipient_postcode', models.CharField(help_text='Recipient Postcode', max_length=9)),
                ('recipient_fax', models.CharField(help_text='Recipient Fax', max_length=26)),
                ('recipient_phone', models.CharField(blank=True, help_text='Recipient Phone', max_length=26)),
                ('recipient_email', models.EmailField(blank=True, help_text='Recipient Email', max_length=254)),
                ('recipient_phone_verified', models.BooleanField(default=False, help_text='Recipient Phone Verified?')),
                ('recipient_email_verified', models.BooleanField(default=False, help_text='Recipient Email Verified?')),
                ('airline_rego', models.CharField(help_text='Airline/Aircraft rego', max_length=35)),
                ('flignt_no', models.CharField(help_text='Flignt No(s)', max_length=10)),
                ('vessel_name', models.CharField(help_text='Vessel Name/Registration', max_length=35)),
                ('imo_no', models.CharField(help_text="IMO/Lloyd's No", max_length=10)),
                ('departure', models.DateTimeField(help_text='Departure date/time')),
                ('departure_port', models.CharField(help_text='Departure Port', max_length=35)),
                ('arrival', models.DateTimeField(help_text='Arrival date/time')),
                ('arrival_port', models.CharField(help_text='Arrival Port', max_length=35)),
                ('route_info', models.TextField(help_text='Route Info')),
                ('permit_number', models.CharField(blank=True, help_text='Permit No', max_length=10)),
                ('valid_from', models.DateField(help_text='Valid From')),
                ('valid_to', models.DateField(help_text='Valid To')),
                ('assessment_date', models.DateField(blank=True, help_text='Assessment Date')),
                ('assessment', models.TextField(blank=True, help_text='Assessment')),
                ('delegate_date', models.DateField(blank=True, help_text='Delegate Date')),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Approved')], default=1, help_text='Status')),
                ('permit_class_a', models.NullBooleanField(help_text='Is Permit Class A?')),
                ('permit_class_b', models.NullBooleanField(help_text='Is Permit Class B?')),
                ('agent_country', models.ForeignKey(help_text='Agent Coountry', on_delete=django.db.models.deletion.CASCADE, related_name='permit_agent_country', to='address.Country')),
                ('agent_state', models.ForeignKey(help_text='Agent State', on_delete=django.db.models.deletion.CASCADE, related_name='permit_agent_state', to='address.State')),
                ('agent_suburb', models.ForeignKey(help_text='Agent Suburb/Town', on_delete=django.db.models.deletion.CASCADE, related_name='permit_agent_suburb', to='address.Suburb')),
                ('applicant_country', models.ForeignKey(help_text='Applicant Coountry', on_delete=django.db.models.deletion.CASCADE, related_name='permit_applicant_country', to='address.Country')),
                ('applicant_state', models.ForeignKey(help_text='Applicant State', on_delete=django.db.models.deletion.CASCADE, related_name='permit_applicant_state', to='address.State')),
                ('applicant_suburb', models.ForeignKey(help_text='Applicant Suburb/Town', on_delete=django.db.models.deletion.CASCADE, related_name='permit_applicant_suburb', to='address.Suburb')),
                ('assessor', models.ForeignKey(blank=True, help_text='Assessor', on_delete=django.db.models.deletion.CASCADE, related_name='accessor', to='account.Account')),
                ('delegate', models.ForeignKey(blank=True, help_text='Delegate', on_delete=django.db.models.deletion.CASCADE, related_name='delegate', to='account.Account')),
                ('destination', models.ForeignKey(help_text='Place of Destination', on_delete=django.db.models.deletion.CASCADE, related_name='permit_destination', to='address.Suburb')),
                ('origin', models.ForeignKey(help_text='Place of Origin', on_delete=django.db.models.deletion.CASCADE, related_name='permit_origin', to='address.Suburb')),
                ('recipient_country', models.ForeignKey(help_text='Recipient Coountry', on_delete=django.db.models.deletion.CASCADE, related_name='permit_recipient_country', to='address.Country')),
                ('recipient_state', models.ForeignKey(help_text='Recipient State', on_delete=django.db.models.deletion.CASCADE, related_name='permit_recipient_state', to='address.State')),
                ('recipient_suburb', models.ForeignKey(help_text='Recipient Suburb/Town', on_delete=django.db.models.deletion.CASCADE, related_name='permit_recipient_suburb', to='address.Suburb')),
            ],
            options={
                'verbose_name': 'Permit',
                'verbose_name_plural': 'Permits',
            },
        ),
        migrations.CreateModel(
            name='PermitStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_date', models.DateField(help_text='Date of action')),
                ('new_status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Approved')], help_text='New status set')),
                ('notes', models.TextField(help_text='Notes')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permit.Permit')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'verbose_name': 'Permit Status Change',
                'verbose_name_plural': 'Permit Status Changes',
            },
        ),
    ]
