# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('permit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField(default=datetime.date.today, help_text='Inspection date')),
                ('findings', models.CharField(default='', help_text='Findings', max_length=200)),
                ('status', models.CharField(default='', help_text='Status', max_length=50)),
                ('biosecurity_concerns', models.TextField(default='', help_text='Biosecurity concerns', max_length=400)),
                ('noncompliance_details', models.TextField(default='', help_text='Noncompliance Details', max_length=400)),
                ('inspection_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_officers', to='account.Account')),
                ('permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='permit.Permit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitExtClassA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Common/Product name', max_length=100)),
                ('description', models.TextField(default='', help_text='Description of Goods', max_length=400)),
                ('genus', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, help_text='Genus')),
                ('vessel_name', models.CharField(blank=True, help_text='Vessel name/Registration', max_length=100, null=True)),
                ('species', models.CharField(default='', help_text='Species', max_length=100)),
                ('brand', models.CharField(blank=True, help_text='Brand name', max_length=100, null=True)),
                ('strain', models.CharField(default='', help_text='Strain/Variety/Cultivator', max_length=100)),
                ('ingredients', models.TextField(blank=True, help_text='Ingredients', max_length=400, null=True)),
                ('quantity', models.CharField(default='', help_text='Quantity', max_length=100)),
                ('units', models.CharField(default='', help_text='Units', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermitExtClassB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Common name', max_length=100)),
                ('description', models.TextField(default='', help_text='Description of Goods', max_length=400)),
                ('breed', models.CharField(default='', help_text='Breed', max_length=100)),
                ('animal_name', models.CharField(default='', help_text='Name of animal', max_length=100)),
                ('age', models.SmallIntegerField(default=0, help_text='Age')),
                ('month', models.SmallIntegerField(default=0, help_text='Month')),
                ('genus', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, help_text='Genus')),
                ('microchip', models.CharField(default='', help_text='Microchip no.', max_length=100)),
                ('other', models.TextField(default='', help_text='Other', max_length=400)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportingFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(default='', help_text='Supported files type', max_length=50)),
                ('file_storage', models.ForeignKey(help_text='File', on_delete=django.db.models.deletion.CASCADE, to='permit.FileStorage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
