# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170519_0825'),
        ('permit', '0003_auto_20170519_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_account',
            field=models.ForeignKey(blank=True, help_text='Applicant Account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_account', to='account.Account'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_draft',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(default=False, on=('applicant_account',)),
        ),
        migrations.AlterField(
            model_name='application',
            name='assessor',
            field=models.ForeignKey(blank=True, help_text='Assessor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessor', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='application',
            name='delegate',
            field=models.ForeignKey(blank=True, help_text='Delegate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegate', to='account.Account'),
        ),
    ]
