# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0004_auto_20170519_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(blank=True, help_text='Applicant Name', max_length=70),
        ),
        migrations.AlterField(
            model_name='application',
            name='assessment_date',
            field=models.DateField(blank=True, help_text='Assessment Date', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='delegate_date',
            field=models.DateField(blank=True, help_text='Delegate Date', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Valid From', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Valid To', null=True),
        ),
    ]
